services:
  dt-labs:
    build: .
    container_name: dt-labs
    restart: always
    env_file:
      - .env

    ports:
      - 5432:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
